-- CreateEnum
CREATE TYPE "BookComplain" AS ENUM ('INCORRECT_INFORMATION', 'COPYRIGHT_VIOLATION', 'OFFENSIVE_CONTENT', 'FRAUD_OR_SUSPICIOUS_BEHAVIOR', 'SPAM_OR_ADVERTISING', 'DUPLICATE_LISTING', 'PROHIBITED_ITEM', 'SEXUAL_OR_INAPPROPRIATE_CONTENT');

-- CreateTable
CREATE TABLE "BookComplaint" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" "BookComplain" NOT NULL,
    "message" TEXT,
    "bookId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "BookComplaint_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "BookComplaint" ADD CONSTRAINT "BookComplaint_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BookComplaint" ADD CONSTRAINT "BookComplaint_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
